# Let's Encrypt ACME
SecRule REQUEST_URI \
    "@beginsWith /.well-known/acme-challenge/" \
    "id:2000,phase:1,pass,nolog,ctl:ruleEngine=Off"

# 健康检查
SecRule REQUEST_URI "@rx ^/(health|ping|status)$" \
    "id:2001,phase:1,pass,nolog,ctl:ruleEngine=Off"
